#!/usr/bin/env python3
"""
K38 足球监控 — 种子数据生成器
生成模拟比赛数据用于本地开发调试
"""

from datetime import datetime, timedelta

# 模拟比赛数据
SEED_MATCHES = [
    {
        "fixture_id": 1001,
        "league_id": 39,
        "league_name": "英超",
        "season": "2025",
        "round": "第38轮",
        "match_date": datetime.now().isoformat(),
        "status": "Second Half",
        "elapsed": 62,
        "home_team": "利物浦",
        "away_team": "曼城",
        "home_team_id": 40,
        "away_team_id": 50,
        "home_goals": 2,
        "away_goals": 1,
        "halftime_home": 1,
        "halftime_away": 0,
        "fulltime_home": None,
        "fulltime_away": None,
        "extra_home": None,
        "extra_away": None,
        "penalty_home": None,
        "penalty_away": None,
        "referee": "Michael Oliver",
        "venue": "安菲尔德球场",
        "stats": {
            "Ball Possession_40": "58%",
            "Ball Possession_50": "42%",
            "Total Shots_40": "12",
            "Total Shots_50": "8",
            "Shots on Goal_40": "5",
            "Shots on Goal_50": "3",
            "Corner Kicks_40": "6",
            "Corner Kicks_50": "3",
        },
        "events": [
            {"time": 23, "type": "Goal", "detail": " Salah (pen)", "team": "利物浦", "player": "Mohamed Salah"},
            {"time": 41, "type": "Goal", "detail": " Nunez", "team": "利物浦", "player": "Darwin Nunez"},
            {"time": 55, "type": "Goal", "detail": " Haaland", "team": "曼城", "player": "Erling Haaland"},
            {"time": 60, "type": "Card", "detail": "Yellow Card", "team": "曼城", "player": "Rodri"},
        ],
    },
    {
        "fixture_id": 1002,
        "league_id": 140,
        "league_name": "西甲",
        "season": "2025",
        "round": "第35轮",
        "match_date": datetime.now().isoformat(),
        "status": "Halftime",
        "elapsed": 45,
        "home_team": "巴塞罗那",
        "away_team": "皇家马德里",
        "home_team_id": 529,
        "away_team_id": 541,
        "home_goals": 1,
        "away_goals": 0,
        "halftime_home": 1,
        "halftime_away": 0,
        "fulltime_home": None,
        "fulltime_away": None,
        "extra_home": None,
        "extra_away": None,
        "penalty_home": None,
        "penalty_away": None,
        "referee": "Jose Sanchez",
        "venue": "诺坎普球场",
        "stats": {
            "Ball Possession_529": "55%",
            "Ball Possession_541": "45%",
            "Total Shots_529": "7",
            "Total Shots_541": "5",
            "Shots on Goal_529": "3",
            "Shots on Goal_541": "2",
        },
        "events": [
            {"time": 32, "type": "Goal", "detail": " Yamal", "team": "巴塞罗那", "player": "Lamine Yamal"},
        ],
    },
    {
        "fixture_id": 1003,
        "league_id": 135,
        "league_name": "意甲",
        "season": "2025",
        "round": "第36轮",
        "match_date": (datetime.now() - timedelta(hours=3)).isoformat(),
        "status": "Match Finished",
        "elapsed": 90,
        "home_team": "AC米兰",
        "away_team": "国际米兰",
        "home_team_id": 489,
        "away_team_id": 505,
        "home_goals": 3,
        "away_goals": 2,
        "halftime_home": 1,
        "halftime_away": 1,
        "fulltime_home": 3,
        "fulltime_away": 2,
        "extra_home": None,
        "extra_away": None,
        "penalty_home": None,
        "penalty_away": None,
        "referee": "Daniele Doveri",
        "venue": "圣西罗球场",
        "stats": {
            "Ball Possession_489": "48%",
            "Ball Possession_505": "52%",
            "Total Shots_489": "14",
            "Total Shots_505": "16",
            "Shots on Goal_489": "6",
            "Shots on Goal_505": "7",
        },
        "events": [
            {"time": 12, "type": "Goal", "detail": " Leao", "team": "AC米兰", "player": "Rafael Leao"},
            {"time": 28, "type": "Goal", "detail": " Lautaro", "team": "国际米兰", "player": "Lautaro Martinez"},
            {"time": 55, "type": "Goal", "detail": " Giroud", "team": "AC米兰", "player": "Olivier Giroud"},
            {"time": 67, "type": "Goal", "detail": " Thuram", "team": "国际米兰", "player": "Marcus Thuram"},
            {"time": 82, "type": "Goal", "detail": " Pulisic (pen)", "team": "AC米兰", "player": "Christian Pulisic"},
        ],
    },
    {
        "fixture_id": 1004,
        "league_id": 78,
        "league_name": "德甲",
        "season": "2025",
        "round": "第34轮",
        "match_date": (datetime.now() + timedelta(hours=6)).isoformat(),
        "status": "Not Started",
        "elapsed": 0,
        "home_team": "拜仁慕尼黑",
        "away_team": "多特蒙德",
        "home_team_id": 157,
        "away_team_id": 165,
        "home_goals": None,
        "away_goals": None,
        "halftime_home": None,
        "halftime_away": None,
        "fulltime_home": None,
        "fulltime_away": None,
        "extra_home": None,
        "extra_away": None,
        "penalty_home": None,
        "penalty_away": None,
        "referee": "Daniel Siebert",
        "venue": "安联球场",
        "stats": {},
        "events": [],
    },
    {
        "fixture_id": 1005,
        "league_id": 1,
        "league_name": "2026世界杯",
        "season": "2026",
        "round": "小组赛A组",
        "match_date": (datetime.now() + timedelta(days=14)).isoformat(),
        "status": "Not Started",
        "elapsed": 0,
        "home_team": "中国",
        "away_team": "巴西",
        "home_team_id": 2000,
        "away_team_id": 2001,
        "home_goals": None,
        "away_goals": None,
        "halftime_home": None,
        "halftime_away": None,
        "fulltime_home": None,
        "fulltime_away": None,
        "extra_home": None,
        "extra_away": None,
        "penalty_home": None,
        "penalty_away": None,
        "referee": "TBD",
        "venue": "国家体育场（鸟巢）",
        "stats": {},
        "events": [],
    },
]
